name = "zodia"
main = ".next/static/chunks/pages/_app.js"
compatibility_date = "2024-05-08"

[[d1_databases]]
binding = "DB" # Este nombre es el que usaremos en el código
database_name = "zodia_db"
database_id = "tu-id-de-base-de-datos-aparecera-aqui"